/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   zip-validator.js
 */

import {IronValidatorBehavior} from '@polymer/iron-validator-behavior/iron-validator-behavior.js';

import {Polymer} from '@polymer/polymer/lib/legacy/polymer-fn.js';

import {LegacyElementMixin} from '@polymer/polymer/lib/legacy/legacy-element-mixin.js';

interface ZipValidatorElement extends IronValidatorBehavior, LegacyElementMixin, HTMLElement {
  validate(value: any): any;
}

export {ZipValidatorElement};

declare global {

  interface HTMLElementTagNameMap {
    "zip-validator": ZipValidatorElement;
  }
}
