/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   date-validator.js
 */

import {IronValidatorBehavior} from '@polymer/iron-validator-behavior/iron-validator-behavior.js';

import {Polymer} from '@polymer/polymer/lib/legacy/polymer-fn.js';

import {LegacyElementMixin} from '@polymer/polymer/lib/legacy/legacy-element-mixin.js';

interface DateValidatorElement extends IronValidatorBehavior, LegacyElementMixin, HTMLElement {
  validate(date: any): any;
}

export {DateValidatorElement};

declare global {

  interface HTMLElementTagNameMap {
    "date-validator": DateValidatorElement;
  }
}
