/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   date-input.js
 */

import {IronA11yKeysBehavior} from '@polymer/iron-a11y-keys-behavior/iron-a11y-keys-behavior.js';

import {IronValidatableBehavior} from '@polymer/iron-validatable-behavior/iron-validatable-behavior.js';

import {Polymer} from '@polymer/polymer/lib/legacy/polymer-fn.js';

import {html} from '@polymer/polymer/lib/utils/html-tag.js';

import {LegacyElementMixin} from '@polymer/polymer/lib/legacy/legacy-element-mixin.js';

interface DateInputElement extends IronA11yKeysBehavior, IronValidatableBehavior, LegacyElementMixin, HTMLElement {
  keyBindings: object;
  validator: string|null|undefined;

  /**
   * Set to true to mark the input as required.
   */
  required: boolean|null|undefined;

  /**
   * The month component of the date displayed.
   */
  month: number|null|undefined;

  /**
   * The year component of the date displayed.
   */
  year: number|null|undefined;

  /**
   * The date object used by the validator. Has two properties, month and
   * year.
   */
  date: object|null|undefined;
  ariaLabelPrefix: string|null|undefined;

  /**
   * Set to true to disable the month and year input elements.
   */
  disabled: boolean|null|undefined;

  /**
   * Set to true to autofocus the month input element.
   */
  autofocus: boolean|null|undefined;

  /**
   * Bound to the month and year input elements' `inputmode` property.
   */
  inputmode: string|null|undefined;

  /**
   * Set to true to mark the month and year inputs as not editable.
   */
  readonly: boolean|null|undefined;
  validate(): any;
  created(): void;
  _selectYear(): void;
  _computeDate(month: any, year: any): void;
  _computeAriaLabel(dateLabel: any, monthLabel: any): any;
}

export {DateInputElement};

declare global {

  interface HTMLElementTagNameMap {
    "date-input": DateInputElement;
  }
}
